<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>true</UseWindowsForms>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>PropertiesDataBaseKey.snk</AssemblyOriginatorKeyFile>
    <StartupObject />
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <Compile Update="DataBases\DataBasePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\FunctionDataBasePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MaterialsDataBasePage.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MechanicalGUI\CreepControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MechanicalGUI\HardeningControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MetallurgyGUI\CCTControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MetallurgyGUI\DiagramControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\MetallurgyGUI\TTTControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="DataBases\ReactionControl.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <None Update="DataBases\Functions\functions.jsf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DataBases\Materials\Materials_v4.jsf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="DataBases\Materials\Materials_v6.jsf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.1.0" />
    <PackageReference Include="DocumentFormat.OpenXml.Framework" Version="3.1.0" />
    <PackageReference Include="MathNet.Numerics.Signed" Version="5.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="PropertiesCalculator" Version="1.0.6" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Runtime.CompilerServices.Unsafe" Version="6.1.2" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="DataBases\Functions\functions_draft.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="DataBases\Materials\materials_draft.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\UserControlEx\UserControlsEx.csproj" />
  </ItemGroup>
</Project>