<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="BazisAvaloniaGUI.Tests" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.0" />
    <PackageReference Include="OperationalController" Version="4.10.5" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="PropertiesCalculator" Version="1.1.2" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SceneCore\SceneCore.csproj" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Navigator\Assets\*.png" />
    <Content Include="..\GUI\DataBases\Materials\materials_draft.txt" Link="DataBases\Materials\materials_draft.txt" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\GUI\DataBases\Functions\functions_draft.txt" Link="DataBases\Functions\functions_draft.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
